server:
  port: 5501

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:mysql://ms-flights-db:3306/ms?serverTimezone=UTC
#    username: root
#    password: aha-0987
    hikari:
       minimum-idle: 2
       maximum-pool-size: 20
       idle-timeout: 30000
       pool-name: SpringBootHikariCP
       max-lifetime: 2000000
       connection-timeout: 30000
       
logging:
  level:
    com:
      example:
        flight: debug
      
mybatis:
   mapper-locations: classpath:mapper/*.xml
   type-aliases-package: com.example.flight.dto
   